---
language: python

sudo: required
dist: bionic

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.5
      - postgresql-10-postgis-2.5-scripts

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database froide WITH OWNER travis;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;' -d froide

script:
  - python -c "print('hello world')"

