---
language: python

sudo: required
dist: bionic

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      - postgresql-11-postgis-2.5

before_script:
  - sudo systemctl start postgresql@11-main
  - psql -U postgres -c 'create database froide WITH OWNER travis;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;' -d froide

script:
  - python -c "print('hello world')"


